// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MyBudget.Web.AspNet.Controllers
{
    public partial class BudgetDistributionController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BudgetDistributionController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected BudgetDistributionController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ByDistribution()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ByDistribution);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SubmitCheckPoint()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SubmitCheckPoint);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BudgetDistributionController Actions { get { return MVC.BudgetDistribution; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "BudgetDistribution";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "BudgetDistribution";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ByDistribution = "ByDistribution";
            public readonly string SubmitCheckPoint = "SubmitCheckPoint";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ByDistribution = "ByDistribution";
            public const string SubmitCheckPoint = "SubmitCheckPoint";
        }


        static readonly ActionParamsClass_ByDistribution s_params_ByDistribution = new ActionParamsClass_ByDistribution();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ByDistribution ByDistributionParams { get { return s_params_ByDistribution; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ByDistribution
        {
            public readonly string budgetId = "budgetId";
        }
        static readonly ActionParamsClass_SubmitCheckPoint s_params_SubmitCheckPoint = new ActionParamsClass_SubmitCheckPoint();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SubmitCheckPoint SubmitCheckPointParams { get { return s_params_SubmitCheckPoint; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SubmitCheckPoint
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ByDistribution = "ByDistribution";
                public readonly string SubmitCheckPoint = "SubmitCheckPoint";
            }
            public readonly string ByDistribution = "~/Views/BudgetDistribution/ByDistribution.cshtml";
            public readonly string SubmitCheckPoint = "~/Views/BudgetDistribution/SubmitCheckPoint.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_BudgetDistributionController : MyBudget.Web.AspNet.Controllers.BudgetDistributionController
    {
        public T4MVC_BudgetDistributionController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ByDistributionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string budgetId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ByDistribution(string budgetId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ByDistribution);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "budgetId", budgetId);
            ByDistributionOverride(callInfo, budgetId);
            return callInfo;
        }

        [NonAction]
        partial void SubmitCheckPointOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MyBudget.Web.AspNet.Controllers.SubmitCheckPoint model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SubmitCheckPoint(MyBudget.Web.AspNet.Controllers.SubmitCheckPoint model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SubmitCheckPoint);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SubmitCheckPointOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
